type PermissionStaticKeys = {
  [K in keyof typeof Permission]: (typeof Permission)[K] extends Function
    ? never
    : K;
}[Exclude<keyof typeof Permission, "prototype">];

export type PermissionName = PermissionStaticKeys;

export default class Permission {
  static GENERAL = Object.freeze({
    LOGIN: "LOGIN",
    VERIFY_TOKEN: "VERIFY_TOKEN",
    GET_ROLES: "GET_ROLES",
    PING: "PING",
    TEST_API: "TEST_API",
  });

  static TWO_FA = Object.freeze({
    GET_TWO_FA_METHODS: "GET_TWO_FA_METHODS",
    SET_UP_TWO_FA: "SET_UP_TWO_FA",
    VERIFY_TWO_FA: "VERIFY_TWO_FA",
    MODIFY_TWO_FA: "MODIFY_TWO_FA",
    USER_TWO_FA_METHODS: "USER_TWO_FA_METHODS",
  });

  static PROFILE_MANAGEMENT = Object.freeze({
    GET_PROFILE: "GET_PROFILE",
    GET_USER_RIGHTS: "GET_USER_RIGHTS",
    UPDATE_PROFILE: "UPDATE_PROFILE",
    UPLOAD_PROFILE_PICTURE: "UPLOAD_PROFILE_PICTURE",
    DELETE_PROFILE_PICTURE: "DELETE_PROFILE_PICTURE",
    CHANGE_PASSWORD: "CHANGE_PASSWORD",
    FORGOT_PASSWORD: "FORGOT_PASSWORD",
    RESET_PASSWORD: "RESET_PASSWORD",
    SEND_EMAIL_VERIFICATION_LINK: "SEND_EMAIL_VERIFICATION_LINK",
    REQUEST_ACCOUNT_DELETION: "REQUEST_ACCOUNT_DELETION",
  });

  static INCOME_MANAGEMENT = Object.freeze({
    ADD_INCOME: "ADD_INCOME",
    PATCH_INCOME_BY_ID: "PATCH_INCOME_BY_ID",
    DELETE_INCOME_BY_ID: "DELETE_INCOME_BY_ID",
    GET_USER_INCOME: "GET_USER_INCOME",
  });

  static BUDGET_ENUM = Object.freeze({
    GET_FREQUENCY_TYPES: "GET_FREQUENCY_TYPES",
    GET_INCOME_SOURCES: "GET_INCOME_SOURCES",
  });

  static SAVING_MANAGEMENT = Object.freeze({
    ADD_SAVING: "ADD_SAVING",
    PATCH_SAVING_BY_USER_ID: "PATCH_SAVING_BY_USER_ID",
    DELETE_SAVING_BY_USER_ID: "DELETE_SAVING_BY_USER_ID",
    GET_USER_SAVING: "GET_USER_SAVING",
  });

  static BUDGET_PLAN_MANAGEMENT = Object.freeze({
    ADD_BUDGET_PLAN: "ADD_BUDGET_PLAN",
    SUBMIT_USER_BUDGET_PLAN: "SUBMIT_USER_BUDGET_PLAN",
    RECALCULATE_BUDGET_PLAN: "RECALCULATE_BUDGET_PLAN",
    PATCH_BUDGET_PLAN: "PATCH_BUDGET_PLAN",
    GET_BUDGET_PLAN: "GET_BUDGET_PLAN",
    GET_IDEAL_BUDGET_PLAN: "GET_IDEAL_BUDGET_PLAN",
  });

  static EXPENSE_MANAGEMENT = Object.freeze({
    ADD_EXPENSE: "ADD_EXPENSE",
    PATCH_EXPENSE_BY_ID: "PATCH_EXPENSE_BY_ID",
    DELETE_EXPENSE_BY_ID: "DELETE_EXPENSE_BY_ID",
    GET_USER_EXPENSE: "GET_USER_EXPENSE",
  });

  static BUDGET_ALLOCATION_MANAGEMENT = Object.freeze({
    ALLOCATE_BUDGET: "ALLOCATE_BUDGET",
    PATCH_BUDGET_ALLOCATION_BY_ID: "PATCH_BUDGET_ALLOCATION_BY_ID",
    DELETE_BUDGET_ALLOCATION_BY_ID: "DELETE_BUDGET_ALLOCATION_BY_ID",
    GET_BUDGET_ALLOCATION_BY_ID: "GET_BUDGET_ALLOCATION_BY_ID",
    FETCH_FILTERED_BUDGET_ALLOCATIONS: "FETCH_FILTERED_BUDGET_ALLOCATIONS",
    AVAILABLE_INCOME_SAVINGS: "AVAILABLE_INCOME_SAVINGS",
    AVAILABLE_INVESTMENT_SAVINGS: "AVAILABLE_INVESTMENT_SAVINGS",
  });

  static SAFETY_NET_MANAGEMENT = Object.freeze({
    CREATE_SAFETY_NET: "CREATE_SAFETY_NET",
    GET_SAFETY_NET: "GET_SAFETY_NET",
    PATCH_SAFETY_NET: "PATCH_SAFETY_NET",
    DELETE_SAFETY_NET: "DELETE_SAFETY_NET",
    WITHDRAW_FUNDS: "WITHDRAW_FUNDS",
    CONTRIBUTE_FUNDS: "CONTRIBUTE_FUNDS",
  });

  static USER_STAGE_MANAGEMENT = Object.freeze({
    CLONE_STAGE_FOR_USER: "CLONE_STAGE_FOR_USER",
    UPDATE_STAGE_STATUS: "UPDATE_STAGE_STATUS",
    UPDATE_STEP_STATUS: "UPDATE_STEP_STATUS",
    GET_USER_STAGES: "GET_USER_STAGES",
    GET_USER_STEPS: "GET_USER_STEPS",
  });

  static FORM_MANAGEMENT = Object.freeze({
    GET_USER_FORMS: "GET_USER_FORMS",
    UPDATE_USER_FORM: "UPDATE_USER_FORM",
    FETCH_FEEDBACK_FORM: "FETCH_FEEDBACK_FORM",
  });

  static PARTNER_MANAGEMENT = Object.freeze({
    GET_PARTNER: "GET_PARTNER",
    CREATE_PARTNER: "CREATE_PARTNER",
    UPLOAD_PARTNER_THUMBNAIL: "UPLOAD_PARTNER_THUMBNAIL",
    REMOVE_PARTNER_THUMBNAIL: "REMOVE_PARTNER_THUMBNAIL",
    UPDATE_PARTNER: "UPDATE_PARTNER",
    DELETE_PARTNER: "DELETE_PARTNER",
  });

  static PARTNERS_CATEGORY_MANAGEMENT = Object.freeze({
    GET_PARTNER_CATEGORY: "GET_PARTNER_CATEGORY",
    CREATE_PARTNER_CATEGORY: "CREATE_PARTNER_CATEGORY",
    UPDATE_PARTNER_CATEGORY: "UPDATE_PARTNER_CATEGORY",
    DELETE_PARTNER_CATEGORY: "DELETE_PARTNER_CATEGORY",
  });

  static PARTNER_MANAGEMENT_READ_ONLY = Object.freeze({
    GET_PARTNER: "GET_PARTNER",
  });

  static PARTNERS_CATEGORY_MANAGEMENT_READ_ONLY = Object.freeze({
    GET_PARTNER_CATEGORY: "GET_PARTNER_CATEGORY",
  });

  static LEARN_RESOURCES_MANAGEMENT = Object.freeze({
    // Types
    CREATE_LEARN_RESOURCE_TYPE: "CREATE_LEARN_RESOURCE_TYPE",
    UPDATE_LEARN_RESOURCE_TYPE: "UPDATE_LEARN_RESOURCE_TYPE",
    DELETE_LEARN_RESOURCE_TYPE: "DELETE_LEARN_RESOURCE_TYPE",
    GET_LEARN_RESOURCE_TYPE: "GET_LEARN_RESOURCE_TYPE",

    // Tags
    CREATE_LEARN_RESOURCE_TAG: "CREATE_LEARN_RESOURCE_TAG",
    UPDATE_LEARN_RESOURCE_TAG: "UPDATE_LEARN_RESOURCE_TAG",
    DELETE_LEARN_RESOURCE_TAG: "DELETE_LEARN_RESOURCE_TAG",
    GET_LEARN_RESOURCE_TAG: "GET_LEARN_RESOURCE_TAG",

    // Categories
    CREATE_LEARN_RESOURCE_CATEGORY: "CREATE_LEARN_RESOURCE_CATEGORY",
    UPDATE_LEARN_RESOURCE_CATEGORY: "UPDATE_LEARN_RESOURCE_CATEGORY",
    DELETE_LEARN_RESOURCE_CATEGORY: "DELETE_LEARN_RESOURCE_CATEGORY",
    GET_LEARN_RESOURCE_CATEGORY: "GET_LEARN_RESOURCE_CATEGORY",

    // Resources
    CREATE_LEARN_RESOURCE: "CREATE_LEARN_RESOURCE",
    UPLOAD_LEARN_RESOURCE_THUMBNAIL: "UPLOAD_LEARN_RESOURCE_THUMBNAIL",
    REMOVE_LEARN_RESOURCE_THUMBNAIL: "REMOVE_LEARN_RESOURCE_THUMBNAIL",
    UPDATE_LEARN_RESOURCE: "UPDATE_LEARN_RESOURCE",
    DELETE_LEARN_RESOURCE: "DELETE_LEARN_RESOURCE",
    GET_LEARN_RESOURCE: "GET_LEARN_RESOURCE",
    UPDATE_USER_FORM: "UPDATE_USER_FORM",
  });

  static ASSET_MANAGEMENT = Object.freeze({
    CREATE_ASSET: "CREATE_ASSET",
    UPDATE_ASSET: "UPDATE_ASSET",
    UPLOAD_ASSET_IMAGE: "UPLOAD_ASSET_IMAGE",
    DELETE_ASSET: "DELETE_ASSET",
    GET_ASSET: "GET_ASSET",

    // Asset Types
    GET_ASSET_TYPE: "GET_ASSET_TYPE",
    GET_OWNED_BY_LIST: "GET_OWNED_BY_LIST",
  });

  static INVESTMENT_MANAGEMENT = Object.freeze({
    ADD_INVESTMENT: "ADD_INVESTMENT",
    GET_INVESTMENTS: "GET_INVESTMENTS",
    GET_INVESTMENTS_TYPES: "GET_INVESTMENTS_TYPES",
    ALLOCATE_FUNDS_TO_INVESTMENT: "ALLOCATE_FUNDS_TO_INVESTMENT",
    PATCH_INVESTMENT_BY_ID: "PATCH_INVESTMENT_BY_ID",
    DELETE_INVESTMENT_BY_ID: "DELETE_INVESTMENT_BY_ID",
  });
  static SUPER_ANNUATION_MANAGEMENT = Object.freeze({
    CREATE_RETIREMENT_GOAL: "CREATE_RETIREMENT_GOAL",
    PATCH_RETIREMENT_GOAL: "PATCH_RETIREMENT_GOAL",
    DELETE_RETIREMENT_GOAL: "DELETE_RETIREMENT_GOAL",
    GET_RETIREMENT_GOAL: "GET_RETIREMENT_GOAL",
    ADD_SUPER_FUND: "ADD_SUPER_FUND",
    ALLOCATE_FUNDS_TO_SUPER_FUND: "ALLOCATE_FUNDS_TO_SUPER_FUND",
    GET_SUPER_FUNDS: "GET_SUPER_FUNDS",
    PATCH_SUPER_FUND: "PATCH_SUPER_FUND",
    DELETE_SUPER_FUND: "DELETE_SUPER_FUND",
    CREATE_SUPER_HEALTH: "CREATE_SUPER_HEALTH",
    FECTH_SUPER_HEALTH_DETAILS: "FECTH_SUPER_HEALTH_DETAILS",
    PATCH_SUPER_HEALTH: "PATCH_SUPER_HEALTH",
  });
  static LEARN_RESOURCES_MANAGEMENT_READ_ONLY = Object.freeze({
    GET_LEARN_RESOURCE: "GET_LEARN_RESOURCE",
    GET_LEARN_RESOURCE_CATEGORY: "GET_LEARN_RESOURCE_CATEGORY",
    GET_LEARN_RESOURCE_TAG: "GET_LEARN_RESOURCE_TAG",
    GET_LEARN_RESOURCE_TYPE: "GET_LEARN_RESOURCE_TYPE",
  });

  static VAULT_CATEGORY_MANAGEMENT = Object.freeze({
    GET_VAULT_CATEGORY: "GET_VAULT_CATEGORY",
    CREATE_VAULT_CATEGORY: "CREATE_VAULT_CATEGORY",
    UPDATE_VAULT_CATEGORY: "UPDATE_VAULT_CATEGORY",
    DELETE_VAULT_CATEGORY: "DELETE_VAULT_CATEGORY",
  });

  static VAULT_FOLDER_MANAGEMENT = Object.freeze({
    GET_VAULT_FOLDER: "GET_VAULT_FOLDER",
    CREATE_VAULT_FOLDER: "CREATE_VAULT_FOLDER",
    UPDATE_VAULT_FOLDER: "UPDATE_VAULT_FOLDER",
    DELETE_VAULT_FOLDER: "DELETE_VAULT_FOLDER",
  });

  static VAULT_TAGS_MANAGEMENT = Object.freeze({
    GET_VAULT_TAG: "GET_VAULT_TAG",
    CREATE_VAULT_TAG: "CREATE_VAULT_TAG",
    UPDATE_VAULT_TAG: "UPDATE_VAULT_TAG",
    DELETE_VAULT_TAG: "DELETE_VAULT_TAG",
  });

  static VAULT_DOCUMENTS_MANAGEMENT = Object.freeze({
    GET_VAULT_DOCUMENT: "GET_VAULT_DOCUMENT",
    CREATE_VAULT_DOCUMENT: "CREATE_VAULT_DOCUMENT",
    UPDATE_VAULT_DOCUMENT: "UPDATE_VAULT_DOCUMENT",
    DELETE_VAULT_DOCUMENT: "DELETE_VAULT_DOCUMENT",
  });

  static VAULT_AUDIT_LOG_MANAGEMENT = Object.freeze({
    FETCH_AUDIT_LOGS: "FETCH_AUDIT_LOGS",
  });

  static DEBT_MANAGEMENT = Object.freeze({
    CREATE_DEBT: "CREATE_DEBT",
    PATCH_DEBT: "PATCH_DEBT",
    DELETE_DEBT: "DELETE_DEBT",
    GET_USER_DEBTS: "GET_USER_DEBTS",
    ADD_DEBT_PAYMENT: "ADD_DEBT_PAYMENT",
    PATCH_DEBT_ACCELERATOR: "PATCH_DEBT_ACCELERATOR",
    DELETE_DEBT_PAYMENT: "DELETE_DEBT_PAYMENT",
    PATCH_DEBT_PAYMENT: "PATCH_DEBT_PAYMENT",
    GET_DEBT_PAYMENTS: "GET_DEBT_PAYMENTS",
    CREATE_DEBT_ACCELERATOR: "CREATE_DEBT_ACCELERATOR",
  });

  static SAVINGS_PLAN_MANAGEMENT = Object.freeze({
    CREATE_GOAL: "CREATE_GOAL",
    GET_USER_GOALS: "GET_USER_GOALS",
    PATCH_USER_GOAL: "PATCH_USER_GOAL",
    DELETE_USER_GOAL: "DELETE_USER_GOAL",
    ALLOCATE_FUNDS: "ALLOCATE_FUNDS",
    UPLOAD_GOAL_IMAGES: "UPLOAD_GOAL_IMAGES",
    REMOVE_GOAL_IMAGE: "REMOVE_GOAL_IMAGE",
  });

  static ESTATE_PLANNING_MANAGEMENT = Object.freeze({
    GET_ESTATE_PLANNING: "GET_ESTATE_PLANNING",
    UPDATE_ESTATE_PLANNING_CHECKPOINT: "UPDATE_ESTATE_PLANNING_CHECKPOINT",
    UPLOAD_ESTATE_PLANNING_CHECKPOINT_DOCUMENT:
      "UPLOAD_ESTATE_PLANNING_CHECKPOINT_DOCUMENT",
    REMOVE_ESTATE_PLANNING_CHECKPOINT_DOCUMENT:
      "REMOVE_ESTATE_PLANNING_CHECKPOINT_DOCUMENT",

    // Template
    UPDATE_ESTATE_PLANNING_TEMPLATE: "UPDATE_ESTATE_PLANNING_TEMPLATE",
  });

  static SUBSCRIPTION_MANAGEMENT = Object.freeze({
    GET_SUBSCRIPTION_PLANS: "GET_SUBSCRIPTION_PLANS",
    PURCHASE_SUBSCRIPTION: "PURCHASE_SUBSCRIPTION",
    UPDATE_CARD: "UPDATE_CARD",
    RENEW_SUBSCRIPTION: "RENEW_SUBSCRIPTION",
    MANUAL_PAYMENT: "MANUAL_PAYMENT",
    CRON_ALERTS: "CRON_ALERTS",
    CANCEL_SUBSCRIPTION: "CANCEL_SUBSCRIPTION",
    FETCH_SUBSCRIPTION_PAYMENTS: "FETCH_SUBSCRIPTION_PAYMENTS",
    DOWNLOAD_INVOICE: "DOWNLOAD_INVOICE",
    REGENERATE_INVOICE: "REGENERATE_INVOICE",
    FETCH_USER_SUBSCRIPTION_DETAILS: "FETCH_USER_SUBSCRIPTION_DETAILS",
    FETCH_SUBSCRIPTION_BANNER: "FETCH_SUBSCRIPTION_BANNER",
    GET_TRIAL_STATUS: "GET_TRIAL_STATUS",
  });

  static CRON_MANAGEMENT = Object.freeze({
    EXTEND_TRIAL_PERIOD: "EXTEND_TRIAL_PERIOD",
    PROCESS_EXPIRING_SUBSCRIPTIONS: "PROCESS_EXPIRING_SUBSCRIPTIONS",
    CRON_ALERTS: "CRON_ALERTS",
    LOGIN: "LOGIN",
  });

  static SUBSCRIPTION_MANAGEMENT_ADMIN = Object.freeze({
    EXTEND_TRIAL_PERIOD: "EXTEND_TRIAL_PERIOD",
    EXTEND_SUBSCRIPTION_PERIOD: "EXTEND_SUBSCRIPTION_PERIOD",
  });

  static INSURANCE_POLICY_MANAGEMENT = Object.freeze({
    GET_INSURANCE_POLICY: "GET_INSURANCE_POLICY",
    CREATE_INSURANCE_POLICY: "CREATE_INSURANCE_POLICY",
    UPDATE_INSURANCE_POLICY: "UPDATE_INSURANCE_POLICY",
    DELETE_INSURANCE_POLICY: "DELETE_INSURANCE_POLICY",
    GET_INSURANCE_POLICY_TYPE: "GET_INSURANCE_POLICY_TYPE",
    REMOVE_INSURANCE_POLICY_DOCUMENT: "REMOVE_INSURANCE_POLICY_DOCUMENT",
  });

  static CHALLENGE_MANAGEMENT = Object.freeze({
    GET_SYSTEM_CHALLENGES: "GET_SYSTEM_CHALLENGES",
    GET_CHALLENGE: "GET_CHALLENGE",
    CREATE_CHALLENGE: "CREATE_CHALLENGE",
    UPDATE_CHALLENGE: "UPDATE_CHALLENGE",
  });

  static BADGE_MANAGEMENT = Object.freeze({
    GET_SYSTEM_BADGES: "GET_SYSTEM_BADGES",
    GET_BADGE: "GET_BADGE",
    CREATE_BADGE: "CREATE_BADGE",
  });

  static CUSTOMER_MANAGEMENT = Object.freeze({
    GET_CUSTOMER: "GET_CUSTOMER",
    GET_FILTERED_CUSTOMER_PAYMENTS: "GET_FILTERED_CUSTOMER_PAYMENTS",
    UPDATE_CUSTOMER: "UPDATE_CUSTOMER",
  });

  static DASHBOARD_MANAGEMENT = Object.freeze({
    GET_BUDGET_PLAN_INSIGHTS: "GET_BUDGET_PLAN_INSIGHTS",
    GET_SAFETY_NET_INSIGHTS: "GET_SAFETY_NET_INSIGHTS",
    GET_DEBT_INSIGHTS: "GET_DEBT_INSIGHTS",
    GET_SAVINGS_PLAN_INSIGHTS: "GET_SAVINGS_PLAN_INSIGHTS",
    GET_SUPER_INSIGHTS: "GET_SUPER_INSIGHTS",
    GET_INVESTMENT_INSIGHTS: "GET_INVESTMENT_INSIGHTS",
    GET_INSURANCE_INSIGHTS: "GET_INSURANCE_INSIGHTS",
    GET_ASSETS_INSIGHTS: "GET_ASSETS_INSIGHTS",
    GET_ESTATE_PLANNING_INSIGHTS: "GET_ESTATE_PLANNING_INSIGHTS",
    GET_DASHBOARD_OVERVIEW: "GET_DASHBOARD_OVERVIEW",
  });

  static ANALYTICS = Object.freeze({
    GET_SUMMARY: "GET_SUMMARY",
    GET_RECENT_ACTIVITIES_LIST: "GET_RECENT_ACTIVITIES_LIST",
  });

  static USER_EXPENSES_MANAGEMENT = Object.freeze({
    CREATE_USER_EXPENSE: "CREATE_USER_EXPENSE",
    ALLOCATE_USER_FUNDS: "ALLOCATE_USER_FUNDS",
    UPDATE_USER_EXPENSE: "UPDATE_USER_EXPENSE",
    DELETE_USER_EXPENSE: "DELETE_USER_EXPENSE",
    GET_USER_EXPENSE: "GET_USER_EXPENSE",
    GET_USER_ALLOCATIONS: "GET_USER_ALLOCATIONS",
  });
  static getPermissionRights(module: PermissionName) {
    return this[module];
  }
}
