# required metadata
sonar.projectKey=obiemoney
sonar.projectName=Obiemoney API
sonar.host.url=http://localhost:9000
sonar.projectVersion=1.0.0
sonar.sourceEncoding=UTF-8
sonar.eslint.eslintconfigpath=.eslintrc.js

# path to source directories
sonar.sources=src

# coverage report
sonar.javascript.lcov.reportPaths=coverage/lcov.info
